In [1]:
# generate marks for 50 students
import numpy as np
marks=np.random.randint(0,101,50)
print(marks)

[98 92 47 66  4  4 47 63 84  5 25 51 19 45 75 82 67 51 48  8 85 82 50 89
 40 95 90 80 47 77 37 73 80 48 37 23 39 13 11 34 82 52  2 27 47 66 39  2
 12 23]


In [2]:
# calculate total, average highest,lowest
import numpy as np
marks=np.array([78,45,92,61,35])
print("Total:",np.sum(marks))
print("Average:",np.mean(marks))
print("Highest:",np.max(marks))
print("Lowest:",np.min(marks))

Total: 311
Average: 62.2
Highest: 92
Lowest: 35


In [3]:
# count above 75,below 35, between 35-75
import numpy as np
marks=np.array([78,45,92,61,35,84,20,75])
print("Above 75:",np.sum(marks>75))
print("Below 35:",np.sum(marks<35))
print("Between 35-75:",np.sum((marks>=35)&(marks<=75)))

Above 75: 3
Below 35: 1
Between 35-75: 4


In [4]:
# assign grades
import numpy as np
marks=np.array([95,82,74,66,58,40])
grades=np.where(marks>=90,'A',
       np.where(marks>=75,'B',
       np.where(marks>=60,'C',
       np.where(marks>=35,'D',
'F'))))
print("Marks:",marks)
print("Grades:",grades)

Marks: [95 82 74 66 58 40]
Grades: ['A' 'B' 'C' 'C' 'D' 'D']


In [5]:
# display top 5 marks
import numpy as np
marks=np.array([78,45,39,20,65,70,98,23])
top5=np.sort(marks)[-5:][::-1]
print(top5)

[98 78 70 65 45]


In [6]:
# display bottom 5 marks
import numpy as np
marks=np.array([87,78,45,39,20,65,70,98,23])
bottom5=np.sort(marks)[:5]
print(bottom5)

[20 23 39 45 65]


In [7]:
# find median and standard deviation
import numpy as np
marks=np.array([87,78,45,39,20,65,70,98,23])
print("Median:",np.median(marks))
print("Standard Deviation:",np.std(marks))

Median: 65.0
Standard Deviation: 26.314339141320733


In [8]:
# create 5-subject marks matrix and calculate totals
import numpy as np
marks=np.array([[80,75,90,85,70],[60,65,70,75,80],[90,95,85,80,88]])
print("Marks Matrix:")
print(marks)
total=np.sum(marks,axis=1)
print("Total Marks:",total)

Marks Matrix:
[[80 75 90 85 70]
 [60 65 70 75 80]
 [90 95 85 80 88]]
Total Marks: [400 350 438]


In [9]:
# find topper in each subject
import numpy as np
marks=np.array([[80,75,90,85,70],[60,65,70,75,80],[90,95,85,80,88]])
topper=np.max(marks,axis=0)
print("Top Marks in Each Subject:")
print(topper)

Top Marks in Each Subject:
[90 95 90 85 88]


In [10]:
# generate report card with total, average, percentage and grade
import numpy as np
marks=np.array([80,75,90,85,70])
total=np.sum(marks)
average=np.mean(marks)
percentage=total/5
if percentage>=90:
    grade="A"
elif percentage>=75:
    grade="B"
elif percentage>=60:
    grade="C"
elif percentage>=35:
    grade="D"
else:
    grade="F"
print("Marks:",marks)
print("Total:",total)
print("Average:",average)
print("Percentage:",percentage)
print("Grade:",grade)

Marks: [80 75 90 85 70]
Total: 400
Average: 80.0
Percentage: 80.0
Grade: B
