In [2]:
# import the numpy library and display its versison.
import numpy as np
print(np.__version__)

2.3.5


In [ ]:
# create a numpy array from a python list
import numpy as np
list1=[10,20,30,40,50]
arr=np.array(list1)
print(arr)

In [6]:
# create arrays using zeros(), ones(),and full()
import numpy as np
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.full((2,3),5))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]


In [7]:
# create an identity matrix using eye()
import numpy as np
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# generate arrays using arange()and linspace().
import numpy as np
print(np.arange(1,11))
print(np.linspace(1,10,5))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.    3.25  5.5   7.75 10.  ]


In [9]:
# create a 3*3 matrix with values from 1 to 9
arr=np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# check the shape, sixe, dimensions, and data type
import numpy as np
arr=np. array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Dimension:",arr.ndim)
print("Data Type:",arr.dtype)

Shape: (2, 3)
Size: 6
Dimension: 2
Data Type: int64


In [14]:
# convert an integer arrray into a float array
import numpy as np
arr=np.array([1,2,3,4,5])
float_arr=arr.astype(float)
print(float_arr)

[1. 2. 3. 4. 5.]


In [15]:
# create an array of random integers between 1 to 100.
import numpy as np 
arr=np.random.randint(1,101,10)
print(arr)

[36 46  7 70  8 98 12 15 58  5]


In [16]:
# compare python list and numpy array
import numpy as np
list1=[1,2,3,4]
arr=np.array([1,2,3,4])
print("Python List:",list1)
print("Numpy Array:",arr)

Python List: [1, 2, 3, 4]
Numpy Array: [1 2 3 4]


In [17]:
# access the first, last and middle elements
import numpy as np
arr=np.array([10,20,30,40,50])
print("Fist:",arr[0])
print("Middle:",arr[len(arr)//2])
print("Last:",arr[-1])

Fist: 10
Middle: 30
Last: 50


In [18]:
# extract first 5 elements
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[:5])

[10 20 30 40 50]


In [20]:
# reverse an array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


In [22]:
# reshape a 1D array into 3*4
import numpy as np
arr=np.arange(1,13)
print(arr.reshape(3,4,))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
# flatten a 2D array
import numpy as np
arr=np.array([[1,2],[3,4,]])
print(arr.flatten())

[1 2 3 4]


In [24]:
# transpose a matrix
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [25]:
# find row-wise and column-wise sums
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Row Sum:",arr.sum(axis=1))
print("Column Sum:",arr.sum(axis=0))

Row Sum: [ 6 15]
Column Sum: [5 7 9]


In [26]:
# concatenate arrays horizontally and vertically
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,0]])
print("Horizontal:")
print(np.hstack((a,b)))
print("Vertically:")
print(np.vstack((a,b)))

Horizontal:
[[1 2 3 5 6 7]
 [4 5 6 8 9 0]]
Vertically:
[[1 2 3]
 [4 5 6]
 [5 6 7]
 [8 9 0]]


In [28]:
# split an array
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(np.split(arr,3))

[array([10, 20]), array([30, 40]), array([50, 60])]


In [32]:
# swap the first and last rowsr
import numpy as np
arr=np.array([[1,2],[3,4],[5,6]])
arr[[0,2]]=arr[[2,0]]
print(arr)

[[5 6]
 [3 4]
 [1 2]]


In [33]:
# element-wise arithmetic
import numpy as np
a=np.array([10,20,30])
b=np.array([1,2,3])
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [37]:
# square, square root, cube
import numpy as np
arr=np.array([1,4,9])
print("Square:",np.square(arr))
print("Square Root:",np.sqrt(arr))
print("Cube:",np.power(arr,3))

Square: [ 1 16 81]
Square Root: [1. 2. 3.]
Cube: [  1  64 729]


In [39]:
# find minumum,maximum and average
import numpy as np
arr=np.array([10,20,30,40,50])
print("Minimum:",np.min(arr))
print("Maximum:",np.max(arr))
print("average:",np.mean(arr))

Minimum: 10
Maximum: 50
average: 30.0


In [41]:
# find sum
import numpy as np
arr=np.array([5,15,25,20])
print("Sum:",np.sum(arr))

Sum: 65


In [44]:
#find cumulative sum
import numpy as np
arr=np.array([1,2,3,4,5])
print(np.cumsum(arr))

[ 1  3  6 10 15]


In [45]:
# Dot productf
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.dot(arr1,arr2))

32


In [47]:
# matrix multiplication
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[6,7],[8,9]])
print(np.matmul(a,b))

[[22 25]
 [50 57]]


In [49]:
# Determinant of a 2*2 matrix
import numpy as np
arr=np.array([[2,3],[4,5]])
print(np.linalg.det(arr))

-2.0


In [52]:
# inverse of a matrix
import numpy as np
arr=np.array([[1,2],[3,4]])
print(np.linalg.inv(arr))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [53]:
# standard deviation and variance
import numpy as np
arr=np.array([10,20,30,40,50])
print("Standard Deviation:",np.std(arr))
print("Variance:",np.var(arr))

Standard Deviation: 14.142135623730951
Variance: 200.0


In [54]:
#display even numbers 
import numpy as np
arr=np.array([10,15,20,25,30,35,40])
print(arr[arr %2==0])

[10 20 30 40]


In [56]:
# display odd numbers
import numpy as np
arr=np.array([10,15,20,25,30,35,40])
print(arr[arr %2!=0])

[15 25 35]


In [59]:
# find elements greater than 50
import numpy as np
arr=np.array([25,45,65,55,35,80])
print(arr[arr>50])

[65 55 80]


In [61]:
# Replace negative value with 0
import numpy as np
arr=np.array([10,-5,20,-7,21,-9])
arr[arr<0]=0
print(arr)

[10  0 20  0 21  0]


In [62]:
# count values above average
import numpy as np
arr=np.array([10,20,30,40,50])
avg=np.mean(arr)
print("Average:",avg)
print("Count:",np.sum(arr>avg))

Average: 30.0
Count: 2


In [64]:
#Find duplicates
import numpy as np
arr=np.array([10,20,20,30,40,40,50])
unique,count=np.unique(arr,return_counts=True)
print(unique[count>1])

[20 40]


In [65]:
# remove duplicates
import numpy as np
arr=np.array([10,20,20,30,40,40,50])
print(np.unique(arr))

[10 20 30 40 50]


In [66]:
# sort ascending adn descending
import numpy as np
arr=np.array([40,10,30,20,50])
print("Ascending:",np.sort(arr))
print("Dscending:",np.sort(arr)
[::-1])

Ascending: [10 20 30 40 50]
Dscending: [50 40 30 20 10]


In [67]:
# find indices greater than 75
import numpy as np
arr=np.array([60,80,90,70,85])
print(np.where(arr>75))

(array([1, 2, 4]),)


In [68]:
# replace even numbers with -1
import numpy as np
arr=np.array([10,15,20,25,30])
arr[arr%2==0]=-1
print(arr)

[-1 15 -1 25 -1]


In [69]:
# generate marks for 50 students
import numpy as np
marks=np.random.randint(0,101,50)
print(marks)

[43  1 49 15 97 73 11 82 18 87 97 23 61 15 18 35 40  1 53 24 52  2 34 45
 74 92 85 77 98 37 23 69 19 52 63 23 83 56 24 57 94 83 98 59 63 11 13 77
 15 87]


In [70]:
# calculate total, average highest,lowest
import numpy as np
marks=np.array([78,45,92,61,35])
print("Total:",np.sum(marks))
print("Average:",np.mean(marks))
print("Highest:",np.max(marks))
print("Lowest:",np.min(marks))

Total: 311
Average: 62.2
Highest: 92
Lowest: 35


In [72]:
# count above 75,below 35, between 35-75
import numpy as np
marks=np.array([78,45,92,61,35,84,20,75])
print("Above 75:",np.sum(marks>75))
print("Below 35:",np.sum(marks<35))
print("Between 35-75:",np.sum((marks>=35)&(marks<=75)))

Above 75: 3
Below 35: 1
Between 35-75: 4


In [76]:
# assign grades
import numpy as np
marks=np.array([95,82,74,66,58,40])
grades=np.where(marks>=90,'A',
       np.where(marks>=75,'B',
       np.where(marks>=60,'C',
       np.where(marks>=35,'D',
'F'))))
print("Marks:",marks)
print("Grades:",grades)

Marks: [95 82 74 66 58 40]
Grades: ['A' 'B' 'C' 'C' 'D' 'D']


In [77]:
# display top 5 marks
import numpy as np
marks=np.array([78,45,39,20,65,70,98,23])
top5=np.sort(marks)[-5:][::-1]
print(top5)

[98 78 70 65 45]


In [78]:
# display bottom 5 marks
import numpy as np
marks=np.array([87,78,45,39,20,65,70,98,23])
bottom5=np.sort(marks)[:5]
print(bottom5)

[20 23 39 45 65]


In [79]:
# find median and standard deviation
import numpy as np
marks=np.array([87,78,45,39,20,65,70,98,23])
print("Median:",np.median(marks))
print("Standard Deviation:",np.std(marks))

Median: 65.0
Standard Deviation: 26.314339141320733


In [81]:
# create 5-subject marks matrix and calculate totals
import numpy as np
marks=np.array([[80,75,90,85,70],[60,65,70,75,80],[90,95,85,80,88]])
print("Marks Matrix:")
print(marks)
total=np.sum(marks,axis=1)
print("Total Marks:",total)

Marks Matrix:
[[80 75 90 85 70]
 [60 65 70 75 80]
 [90 95 85 80 88]]
Total Marks: [400 350 438]


In [82]:
# find topper in each subject
import numpy as np
marks=np.array([[80,75,90,85,70],[60,65,70,75,80],[90,95,85,80,88]])
topper=np.max(marks,axis=0)
print("Top Marks in Each Subject:")
print(topper)

Top Marks in Each Subject:
[90 95 90 85 88]


In [83]:
# generate report card with total, average, percentage and grade
import numpy as np
marks=np.array([80,75,90,85,70])
total=np.sum(marks)
average=np.mean(marks)
percentage=total/5
if percentage>=90:
    grade="A"
elif percentage>=75:
    grade="B"
elif percentage>=60:
    grade="C"
elif percentage>=35:
    grade="D"
else:
    grade="F"
print("Marks:",marks)
print("Total:",total)
print("Average:",average)
print("Percentage:",percentage)
print("Grade:",grade)

Marks: [80 75 90 85 70]
Total: 400
Average: 80.0
Percentage: 80.0
Grade: B
